<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personajes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="personaje" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="caracteristicas_fisicas">
                                <xs:complexType>
                                    <xs:attribute name="altura" type="xs:string" use="required"/>
                                    <xs:attribute name="peso" type="xs:string" use="required"/>
                                    <xs:attribute name="color_pelo" type="xs:string" use="required"/>
                                    <xs:attribute name="color_piel" type="xs:string" use="required"/>
                                    <xs:attribute name="color_ojos" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="planeta">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="datos_fisicos">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="superficie">
                                                        <xs:complexType>
                                                            <xs:attribute name="terreno" type="xs:string" use="required"/>
                                                            <xs:attribute name="agua" type="xs:string" use="required"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="periodo_rotacion" type="xs:string" use="required"/>
                                                <xs:attribute name="periodo_orbital" type="xs:string" use="required"/>
                                                <xs:attribute name="diametro" type="xs:string" use="required"/>
                                                <xs:attribute name="clima" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:string" use="required"/>
                                    <xs:attribute name="nombre" type="xs:string" use="required"/>
                                    <xs:attribute name="poblacion" type="xs:string" use="required"/>
                                    <xs:attribute name="idioma" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                        <xs:attribute name="nombre" type="xs:string" use="required"/>
                        <xs:attribute name="anno_nacimiento" type="xs:string" use="required"/>
                        <xs:attribute name="genero" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
